In [1]:
# Print the numpy version and the configuration
import numpy as np
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
np.show_config()

NumPy Version: 1.24.3
NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SiddharthS/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SiddharthS/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SiddharthS/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SiddharthS/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SiddharthS/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SiddharthS/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SiddharthS/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', N

In [2]:
# Initialize a vector that contains numbers from 1 to 20 and reverse it
vec = np.arange(1, 21)
rev_vec = np.flip(vec)
print("Original Vector:", vec)
print("Reversed Vector:", rev_vec)

Original Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reversed Vector: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [3]:
# Create a 3x3 array with random values and find the minimum and maximum value
random_array = np.random.rand(3, 3)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random 3x3 Array:")
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random 3x3 Array:
[[0.26521744 0.95324052 0.47726477]
 [0.76722498 0.28500296 0.90137644]
 [0.97300956 0.79766324 0.57034619]]
Minimum Value: 0.26521744097369504
Maximum Value: 0.9730095571748962


In [4]:
# Consider a (5,5,8) shape array, what is the index (x,y,z) of the 100th element?
arr_shape = (5, 5, 8)
index = np.unravel_index(100, arr_shape)
print("Index of the 100th element:", index)

Index of the 100th element: (2, 2, 4)


In [5]:
# How to find common values between two arrays? Demonstrate.
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("Common Values between array1 and array2:", common_values)

Common Values between array1 and array2: [3 4 5]


In [6]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.
cartesian_coordinates = np.random.rand(10, 2)
x, y = cartesian_coordinates[:, 0], cartesian_coordinates[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coordinates = np.column_stack((r, theta))
print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("Polar Coordinates:")
print(polar_coordinates)

Cartesian Coordinates:
[[0.95163171 0.57465603]
 [0.56561688 0.90961454]
 [0.44752668 0.34921192]
 [0.90885909 0.74816266]
 [0.41270528 0.59359218]
 [0.11303662 0.31490732]
 [0.4362559  0.12844385]
 [0.93680058 0.16949491]
 [0.85191886 0.31048351]
 [0.83924131 0.36507938]]
Polar Coordinates:
[[1.11168002 0.54325576]
 [1.07113074 1.01448673]
 [0.56765226 0.6626223 ]
 [1.17718827 0.68872141]
 [0.72296426 0.96325368]
 [0.33458018 1.22616879]
 [0.45477141 0.28633263]
 [0.95201043 0.17899318]
 [0.90673356 0.34949118]
 [0.91520977 0.41031958]]


In [7]:
# Demonstrate printing all the values of an array
# Printing all values of the random_array created earlier
print("All Values of the random_array:")
print(random_array.ravel())

All Values of the random_array:
[0.26521744 0.95324052 0.47726477 0.76722498 0.28500296 0.90137644
 0.97300956 0.79766324 0.57034619]


In [8]:
# How to convert a float (32 bits) array into an integer (32 bits) in place? [Use NumPy Datatypes]
float_array = np.array([1.5, 2.7, 3.2, 4.8], dtype=np.float32)
int_array = float_array.astype(np.int32)
print("Float Array (32 bits):", float_array)
print("Integer Array (32 bits):", int_array)

Float Array (32 bits): [1.5 2.7 3.2 4.8]
Integer Array (32 bits): [1 2 3 4]
